### ISSUE TITLE
Strip out Cordova

### ISSUE THREAD

**Issue by felixrieseberg** [nitrogenjs/oxide#33]
Cordova is neat, but it should really not be part of this two. Better solution: A see rate two with this one as a submodule.

**Comment by deadlyfingers** [comment]
When running `ember serve` I get the following error (on Mac):
Error thrown while running shell command: "cordova build ios"
Error: Command failed: /bin/sh -c cordova build ios
Error: spawn EACCES

However I can run `ember cordova:open` to open project in Xcode and then run it in the simulator.
Any setup steps I could be missing?

I am running `cordova -v` 4.2.0

**Comment by felixrieseberg** [comment]
Yeah, Cordova is a pain - Ivan was awesome enough to pull Cordova out in his PR #34 - once we can merge it, we can also close this issue.
